server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: smartcode

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:mandestanleys@gmail.com}
    password: ${MAIL_PASSWORD:gkfwcpgrequzdabd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  h2:
    console:
      enabled: true

app:
  internal:
    key: ${X-INTERNAL-KEY:dev-key}